"""Add user relationship to Reservation

Revision ID: 1c8cb0368f66
Revises: 1f71b45deaae
Create Date: 2025-03-04 17:53:55.077705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8cb0368f66'
down_revision: Union[str, None] = '1f71b45deaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_reservation_user_id_user", 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint("fk_reservation_user_id_user", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
