"""Add description to MeetingRoom

Revision ID: 9c7ae3026e71
Revises: ea5e70f9ace8
Create Date: 2025-02-06 08:47:05.594674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7ae3026e71'
down_revision: Union[str, None] = 'ea5e70f9ace8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_room', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_room', 'description')
    # ### end Alembic commands ###
